"""add docs creation areas table

Revision ID: 0090a2d0d35c
Revises: 2f0543b04a6c
Create Date: 2026-07-08 00:14:14.404574

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0090a2d0d35c'
down_revision: Union[str, Sequence[str], None] = '2f0543b04a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_creation_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host_path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_path'),
    schema='company'
    )
    # ### end Alembic commands ###

    # Seed the pre-existing default area so at least one always exists (the
    # invariant the route layer enforces on DELETE) and the Docs page keeps
    # working exactly as before for anyone upgrading.
    docs_creation_areas = sa.table(
        'docs_creation_areas',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('host_path', sa.String()),
        schema='company',
    )
    op.bulk_insert(
        docs_creation_areas,
        [{'id': uuid.uuid4(), 'name': 'Docs', 'host_path': '/root/docs'}],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docs_creation_areas', schema='company')
    # ### end Alembic commands ###
