"""add doc links table

Revision ID: 023b41e1de17
Revises: f30304ecb3f1
Create Date: 2026-07-07 14:39:24.790066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023b41e1de17'
down_revision: Union[str, Sequence[str], None] = 'f30304ecb3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_path', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('product', 'product_version', 'project', 'pipeline', 'planning_item', 'task', 'artifact')", name='ck_doc_links_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_path', 'entity_type', 'entity_id', name='uq_doc_links_doc_entity'),
    schema='company'
    )
    op.create_index(op.f('ix_company_doc_links_doc_path'), 'doc_links', ['doc_path'], unique=False, schema='company')
    op.create_index(op.f('ix_company_doc_links_entity_id'), 'doc_links', ['entity_id'], unique=False, schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_doc_links_entity_id'), table_name='doc_links', schema='company')
    op.drop_index(op.f('ix_company_doc_links_doc_path'), table_name='doc_links', schema='company')
    op.drop_table('doc_links', schema='company')
    # ### end Alembic commands ###
