"""background app testing (WebAutomationTestRun)

Revision ID: 25707ceceaf5
Revises: dc5a14ad229b
Create Date: 2026-07-28 11:13:07.878662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25707ceceaf5'
down_revision: Union[str, Sequence[str], None] = 'dc5a14ad229b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_automation_test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('standalone_app_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='queued', nullable=False),
    sa.Column('bridge_run_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('screenshot_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('background', 'visible')", name='ck_web_automation_test_run_mode'),
    sa.CheckConstraint("status IN ('queued', 'running', 'passed', 'failed', 'error')", name='ck_web_automation_test_run_status'),
    sa.CheckConstraint("triggered_by IN ('slash_command', 'mcp_tool', 'manual')", name='ck_web_automation_test_run_triggered_by'),
    sa.CheckConstraint('(product_id IS NOT NULL AND standalone_app_id IS NULL) OR (product_id IS NULL AND standalone_app_id IS NOT NULL)', name='ck_web_automation_test_run_one_target'),
    sa.ForeignKeyConstraint(['product_id'], ['company.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_id'], ['company.web_automation_routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['standalone_app_id'], ['company.standalone_apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.add_column('web_automation_routines', sa.Column('background_test_enabled', sa.Boolean(), server_default='false', nullable=False), schema='company')
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same unrelated pre-existing drift
    # as prior migrations in this feature (uq_approval_requests_pending_target
    # index, chat_messages.steps column) -- stripped again here for the same
    # reason (see 3696e94e0903/a128eb1942f6's migrations).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_automation_routines', 'background_test_enabled', schema='company')
    op.drop_table('web_automation_test_runs', schema='company')
    # ### end Alembic commands ###
