"""add standalone apps and macro instruction sets

Revision ID: 2664534a504d
Revises: 5f9c3e1a7d64
Create Date: 2026-07-14 03:05:41.534985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2664534a504d'
down_revision: Union[str, Sequence[str], None] = '5f9c3e1a7d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standalone_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_standalone_app_name'),
    schema='company'
    )
    op.create_table('macro_instruction_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('standalone_app_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(product_id IS NOT NULL AND standalone_app_id IS NULL) OR (product_id IS NULL AND standalone_app_id IS NOT NULL)', name='ck_macro_instruction_set_one_target'),
    sa.ForeignKeyConstraint(['product_id'], ['company.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standalone_app_id'], ['company.standalone_apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'standalone_app_id', 'name', name='uq_macro_instruction_set_target_name'),
    schema='company'
    )
    op.add_column('web_automation_routines', sa.Column('standalone_app_id', sa.UUID(), nullable=True), schema='company')
    op.alter_column('web_automation_routines', 'product_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='company')
    op.drop_constraint(op.f('uq_web_automation_routine_product_name'), 'web_automation_routines', schema='company', type_='unique')
    op.create_unique_constraint('uq_web_automation_routine_target_name', 'web_automation_routines', ['product_id', 'standalone_app_id', 'name'], schema='company')
    op.create_foreign_key(None, 'web_automation_routines', 'standalone_apps', ['standalone_app_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_check_constraint(
        'ck_web_automation_routine_one_target', 'web_automation_routines',
        "(product_id IS NOT NULL AND standalone_app_id IS NULL) OR (product_id IS NULL AND standalone_app_id IS NOT NULL)",
        schema='company',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_web_automation_routine_one_target', 'web_automation_routines', schema='company', type_='check')
    op.drop_constraint(None, 'web_automation_routines', schema='company', type_='foreignkey')
    op.drop_constraint('uq_web_automation_routine_target_name', 'web_automation_routines', schema='company', type_='unique')
    op.create_unique_constraint(op.f('uq_web_automation_routine_product_name'), 'web_automation_routines', ['product_id', 'name'], schema='company', postgresql_nulls_not_distinct=False)
    op.alter_column('web_automation_routines', 'product_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='company')
    op.drop_column('web_automation_routines', 'standalone_app_id', schema='company')
    op.drop_table('macro_instruction_sets', schema='company')
    op.drop_table('standalone_apps', schema='company')
    # ### end Alembic commands ###
