"""add agent demands table

Revision ID: 2f0543b04a6c
Revises: 6f2a8b49d3c1
Create Date: 2026-07-07 19:26:07.519242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0543b04a6c'
down_revision: Union[str, Sequence[str], None] = '6f2a8b49d3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_demands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_entity_type', sa.String(length=20), nullable=True),
    sa.Column('converted_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("converted_entity_type IS NULL OR converted_entity_type IN ('task', 'doc', 'artifact', 'knowledge_base')", name='ck_agent_demands_converted_entity_type'),
    sa.CheckConstraint("status IN ('new', 'read', 'converted', 'archived')", name='ck_agent_demands_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_demands', schema='company')
    # ### end Alembic commands ###
