"""Add backup_enabled to projects

Revision ID: 3d5e07b9954f
Revises: 8f2e9b9aa25a
Create Date: 2026-07-11 11:43:14.294883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5e07b9954f'
down_revision: Union[str, Sequence[str], None] = '8f2e9b9aa25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('backup_enabled', sa.Boolean(), server_default='false', nullable=False), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'backup_enabled', schema='company')
    # ### end Alembic commands ###
