"""add workstation peer grants

Revision ID: 40e6bb284f7b
Revises: f661e84915b2
Create Date: 2026-09-07 17:42:04.300948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e6bb284f7b'
down_revision: Union[str, Sequence[str], None] = 'f661e84915b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workstation_peer_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workstation_a_id', sa.UUID(), nullable=False),
    sa.Column('workstation_b_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['company.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstation_a_id'], ['company.workstations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstation_b_id'], ['company.workstations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index('uq_workstation_peer_grants_active_pair', 'workstation_peer_grants', ['workstation_a_id', 'workstation_b_id'], unique=True, schema='company', postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_workstation_peer_grants_active_pair', table_name='workstation_peer_grants', schema='company', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('workstation_peer_grants', schema='company')
    # ### end Alembic commands ###
