"""add user avatar_data_url

Revision ID: 42f382d2b07a
Revises: 481e910bebb1
Create Date: 2026-07-01 00:37:40.703671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f382d2b07a'
down_revision: Union[str, Sequence[str], None] = '481e910bebb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data_url', sa.Text(), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_data_url', schema='company')
    # ### end Alembic commands ###
