"""add chat_session_participants and responding_agent_id

Revision ID: 481e910bebb1
Revises: f7e6f9a04b17
Create Date: 2026-06-30 23:24:44.979641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481e910bebb1'
down_revision: Union[str, Sequence[str], None] = 'f7e6f9a04b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('hermes_session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['company.chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'agent_id', name='uq_chat_session_participants_session_agent'),
    schema='company'
    )
    op.add_column('chat_messages', sa.Column('responding_agent_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(None, 'chat_messages', 'agents', ['responding_agent_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', schema='company', type_='foreignkey')
    op.drop_column('chat_messages', 'responding_agent_id', schema='company')
    op.drop_table('chat_session_participants', schema='company')
    # ### end Alembic commands ###
