"""add demand_groups

Revision ID: 51e69e80a0f7
Revises: cbcca5ec65b3
Create Date: 2026-07-08 18:48:27.132100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e69e80a0f7'
down_revision: Union[str, Sequence[str], None] = 'cbcca5ec65b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['company.demand_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.add_column('agent_demands', sa.Column('group_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(None, 'agent_demands', 'demand_groups', ['group_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_demands', schema='company', type_='foreignkey')
    op.drop_column('agent_demands', 'group_id', schema='company')
    op.drop_table('demand_groups', schema='company')
    # ### end Alembic commands ###
