"""Add backup_location to projects

Revision ID: 56d8b83f8286
Revises: 3d5e07b9954f
Create Date: 2026-07-11 12:21:39.535588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d8b83f8286'
down_revision: Union[str, Sequence[str], None] = '3d5e07b9954f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('backup_location', sa.String(length=1024), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'backup_location', schema='company')
    # ### end Alembic commands ###
