"""add chat_messages thinking_seconds

Revision ID: 5fc38e1b7951
Revises: 42f382d2b07a
Create Date: 2026-07-01 01:28:00.325462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc38e1b7951'
down_revision: Union[str, Sequence[str], None] = '42f382d2b07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('thinking_seconds', sa.Integer(), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'thinking_seconds', schema='company')
    # ### end Alembic commands ###
