"""add entity_type entity_id to policies

Revision ID: 827968624658
Revises: e19cfcf39941
Create Date: 2026-06-30 00:37:45.615190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827968624658'
down_revision: Union[str, Sequence[str], None] = 'e19cfcf39941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # These columns existed only in some pre-migration installations.
    op.execute('ALTER TABLE company.planning_items DROP COLUMN IF EXISTS planned_start_date')
    op.execute('ALTER TABLE company.planning_items DROP COLUMN IF EXISTS planned_end_date')
    op.execute('ALTER TABLE company.planning_items DROP COLUMN IF EXISTS estimated_cost')
    op.add_column('policies', sa.Column('entity_type', sa.String(length=100), nullable=True), schema='company')
    op.add_column('policies', sa.Column('entity_id', sa.UUID(), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade policy fields; restore legacy columns on a best-effort basis.

    Drifted installations may have lacked those columns before this revision,
    so their original defaults cannot be reconstructed. The compatibility
    downgrade is idempotent and does not claim to restore unknown drift.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'entity_id', schema='company')
    op.drop_column('policies', 'entity_type', schema='company')
    op.execute('ALTER TABLE company.planning_items ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC(12, 2)')
    op.execute('ALTER TABLE company.planning_items ADD COLUMN IF NOT EXISTS planned_end_date DATE')
    op.execute('ALTER TABLE company.planning_items ADD COLUMN IF NOT EXISTS planned_start_date DATE')
    # ### end Alembic commands ###
