"""Add github_repo_url to projects

Revision ID: 8f2e9b9aa25a
Revises: 3a69f687b50c
Create Date: 2026-07-11 11:40:58.217007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2e9b9aa25a'
down_revision: Union[str, Sequence[str], None] = '3a69f687b50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo_url', sa.String(length=500), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo_url', schema='company')
    # ### end Alembic commands ###
