"""add tech stack options catalog

Revision ID: 9823e7890ae4
Revises: 0d160dcd7dbb
Create Date: 2026-08-15 18:22:15.482428

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9823e7890ae4'
down_revision: Union[str, Sequence[str], None] = '0d160dcd7dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seed of "org_standard" catalog rows, sourced from Marcelo's knowledge base
# (/root/.hermes/knowledge_base/marcelo/stack/02-UI-DESIGN-SYSTEM-AND-
# TECHNOLOGY-SPEC.md §12 "Seleção de tecnologia frontend", §17 "Seleção
# resumida de backend", §18 "Seleção resumida de dados"). deploy_infra has no
# dedicated menu in that doc -- seeded from the container/orchestration
# options 12-INFRASTRUCTURE-ENVIRONMENT-AND-IAC-STANDARD.md names (Container
# platforms/Kubernetes adoption/Serverless adoption), anchored on Docker
# Compose since that is ForgeHub's own documented deploy baseline
# (docs/TECHNOLOGY.md, CLAUDE.md).
SEED_OPTIONS: list[tuple[str, str, str]] = [
    ("frontend", "React + TypeScript + Vite + Tailwind CSS + shadcn/ui",
     "Aplicação web autenticada (SPA) -- stack padrão da organização."),
    ("frontend", "Next.js + TypeScript + Tailwind CSS + shadcn/ui",
     "Aplicação pública com SEO, SSR ou geração estática."),
    ("frontend", "React + TypeScript + PrimeReact, MUI ou Ant Design",
     "Back-office com muitos dados (tabelas, grids, formulários densos)."),
    ("frontend", "React Native + Expo + TypeScript + NativeWind",
     "Aplicação mobile."),
    ("frontend", "React Native + Expo + Tamagui",
     "Aplicação mobile multiplataforma (alternativa ao NativeWind)."),
    ("backend", "C#/.NET",
     "Core de negócio, APIs críticas e sistemas transacionais."),
    ("backend", "Node.js",
     "BFF, WebSocket e serviços orientados a eventos."),
    ("backend", "Python (FastAPI)",
     "IA, automação, ETL e processamento de dados."),
    ("database", "PostgreSQL", "Banco relacional padrão."),
    ("database", "SQL Server", "Ecossistema Microsoft e ambientes corporativos existentes."),
    ("database", "MongoDB", "Documentos, quando há necessidade comprovada."),
    ("database", "Redis", "Cache, locks, sessões, rate limiting e dados temporários."),
    ("deploy_infra", "Docker Compose (host único)",
     "Deploy simples em host único -- baseline padrão do ForgeHub."),
    ("deploy_infra", "Kubernetes",
     "Orquestração multi-serviço/multi-node, para escala e alta disponibilidade."),
    ("deploy_infra", "VM/bare-metal + systemd",
     "Processo único gerenciado por systemd, sem containers."),
    ("deploy_infra", "Serverless / PaaS gerenciado",
     "Funções ou serviços geridos pelo provedor cloud, sem servidor próprio."),
]

tech_stack_options_table = sa.table(
    'tech_stack_options',
    sa.column('id', sa.UUID()),
    sa.column('layer', sa.String()),
    sa.column('name', sa.String()),
    sa.column('description', sa.Text()),
    sa.column('source', sa.String()),
    schema='company',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_stack_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("layer IN ('frontend', 'backend', 'database', 'deploy_infra')", name='ck_tech_stack_options_layer'),
    sa.CheckConstraint("source IN ('org_standard', 'custom')", name='ck_tech_stack_options_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer', 'name', name='uq_tech_stack_options_layer_name'),
    schema='company'
    )
    # ### end Alembic commands ###

    op.bulk_insert(tech_stack_options_table, [
        {"id": uuid.uuid4(), "layer": layer, "name": name, "description": description, "source": "org_standard"}
        for layer, name, description in SEED_OPTIONS
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_stack_options', schema='company')
    # ### end Alembic commands ###
