"""add mcp catalog and project mcp servers

Revision ID: a128eb1942f6
Revises: 7768a936e179
Create Date: 2026-07-28 09:30:47.722925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a128eb1942f6'
down_revision: Union[str, Sequence[str], None] = '7768a936e179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_catalog_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('apply_to_all_agents', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transport IN ('stdio', 'http')", name='ck_mcp_catalog_servers_transport'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('mcp_catalog_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_server_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('agent', 'project')", name='ck_mcp_catalog_assignments_target_type'),
    sa.ForeignKeyConstraint(['catalog_server_id'], ['company.mcp_catalog_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_server_id', 'target_type', 'target_id', name='uq_mcp_catalog_assignments_target'),
    schema='company'
    )
    op.create_table('project_mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('runtime_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("runtime_type IN ('claude')", name='ck_project_mcp_servers_runtime_type'),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'runtime_type', 'name', name='uq_project_mcp_servers_target'),
    schema='company'
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected an unrelated pre-existing drift here
    # (a dropped 'uq_approval_requests_pending_target' index and a dropped
    # 'chat_messages.steps' column) -- both stripped from this migration.
    # That drift is unrelated to this feature and shouldn't be silently
    # folded into an unrelated migration; investigate/fix separately.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_mcp_servers', schema='company')
    op.drop_table('mcp_catalog_assignments', schema='company')
    op.drop_table('mcp_catalog_servers', schema='company')
    # ### end Alembic commands ###
