"""add ssh_key_path to servers

Revision ID: b4a30fa38d08
Revises: 32b44a72b5e2
Create Date: 2026-07-01 02:52:08.621695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a30fa38d08'
down_revision: Union[str, Sequence[str], None] = '32b44a72b5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ssh_key_path', sa.String(length=500), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'ssh_key_path', schema='company')
    # ### end Alembic commands ###
