"""add agent questions

Revision ID: d447cad24782
Revises: e0724593b280
Create Date: 2026-10-02 23:57:56.360352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd447cad24782'
down_revision: Union[str, Sequence[str], None] = 'e0724593b280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('relay_agent_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin_demand_id', sa.UUID(), nullable=True),
    sa.Column('notify_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telegram_chat', sa.String(length=100), nullable=True),
    sa.Column('telegram_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_error', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_via', sa.String(length=20), nullable=True),
    sa.Column('answered_by', sa.String(length=100), nullable=True),
    sa.Column('reply_demand_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'answered') = (answer IS NOT NULL AND answered_at IS NOT NULL)", name='ck_agent_questions_answer_present'),
    sa.CheckConstraint("answered_via IS NULL OR answered_via IN ('telegram', 'screen')", name='ck_agent_questions_answered_via'),
    sa.CheckConstraint("status IN ('pending', 'answered', 'cancelled')", name='ck_agent_questions_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_demand_id'], ['company.agent_demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relay_agent_id'], ['company.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_demand_id'], ['company.agent_demands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    schema='company'
    )
    op.create_index(op.f('ix_company_agent_questions_agent_id'), 'agent_questions', ['agent_id'], unique=False, schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_agent_questions_agent_id'), table_name='agent_questions', schema='company')
    op.drop_table('agent_questions', schema='company')
    # ### end Alembic commands ###
