"""add agent operations domain

Revision ID: e0724593b280
Revises: c5e7a9b1d3f2
Create Date: 2026-10-02 22:35:49.601131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0724593b280'
down_revision: Union[str, Sequence[str], None] = 'c5e7a9b1d3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version'),
    schema='company'
    )
    op.create_table('agent_charters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monitored_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coordinates_with', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('never_does', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_run_budget', sa.Integer(), nullable=False),
    sa.Column('daily_cost_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('escalation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("escalation IN ('telegram_direct', 'via_athos')", name='ck_agent_charters_escalation'),
    sa.CheckConstraint('daily_cost_budget >= 0', name='ck_agent_charters_cost_budget'),
    sa.CheckConstraint('daily_run_budget >= 0', name='ck_agent_charters_run_budget'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id'),
    schema='company'
    )
    op.create_table('agent_routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('linked_audit_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('last_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('monitoring', 'maintenance', 'improvement', 'report', 'coordination')", name='ck_agent_routines_kind'),
    sa.CheckConstraint('deadline_minutes > 0', name='ck_agent_routines_deadline'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index(op.f('ix_company_agent_routines_agent_id'), 'agent_routines', ['agent_id'], unique=False, schema='company')
    op.create_table('agent_routine_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('demand_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'running', 'completed', 'failed', 'missed', 'skipped_budget')", name='ck_agent_routine_runs_status'),
    sa.ForeignKeyConstraint(['demand_id'], ['company.agent_demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['company.agent_routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'occurrence_at', name='uq_agent_routine_runs_occurrence'),
    schema='company'
    )
    op.create_index(op.f('ix_company_agent_routine_runs_routine_id'), 'agent_routine_runs', ['routine_id'], unique=False, schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_agent_routine_runs_routine_id'), table_name='agent_routine_runs', schema='company')
    op.drop_table('agent_routine_runs', schema='company')
    op.drop_index(op.f('ix_company_agent_routines_agent_id'), table_name='agent_routines', schema='company')
    op.drop_table('agent_routines', schema='company')
    op.drop_table('agent_charters', schema='company')
    op.drop_table('operations_policies', schema='company')
    # ### end Alembic commands ###
