"""add client workstation irregularity

Revision ID: e9ae96a2c664
Revises: 4e9d9c51a7b2
Create Date: 2026-09-06 10:59:07.525772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ae96a2c664'
down_revision: Union[str, Sequence[str], None] = '4e9d9c51a7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('support_plan', sa.String(length=20), nullable=True),
    sa.Column('headscale_tag', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("support_plan IS NULL OR support_plan IN ('4h', '8h', '12h')", name='ck_clients_support_plan'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headscale_tag'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('workstations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os_kind', sa.String(length=20), nullable=False),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_token_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_token_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_agent_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("os_kind IN ('linux', 'windows')", name='ck_workstations_os_kind'),
    sa.ForeignKeyConstraint(['client_id'], ['company.clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token_hash'),
    schema='company'
    )
    op.create_table('irregularities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workstation_id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_key IN ('disk_space_low', 'backup_stale', 'unauthorized_remote_tool', 'critical_service_down', 'collection_failed', 'agent_unreachable')", name='ck_irregularities_rule_key'),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_irregularities_severity'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_irregularities_status'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['company.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstation_id'], ['company.workstations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irregularities', schema='company')
    op.drop_table('workstations', schema='company')
    op.drop_table('clients', schema='company')
    # ### end Alembic commands ###
