"""add audit checks tables

Revision ID: f30304ecb3f1
Revises: a6d95c31e7f2
Create Date: 2026-07-07 08:47:25.971230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30304ecb3f1'
down_revision: Union[str, Sequence[str], None] = 'a6d95c31e7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('workdir', sa.String(length=500), nullable=True),
    sa.Column('agent_profile', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('audit_check_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'fail', 'error', 'timeout')", name='ck_audit_check_runs_status'),
    sa.ForeignKeyConstraint(['check_id'], ['company.audit_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index(op.f('ix_company_audit_check_runs_check_id'), 'audit_check_runs', ['check_id'], unique=False, schema='company')
    # NOTE: autogenerate also proposed dropping ix_notifications_occurred_at
    # (model/db drift, fixed by declaring the index on the model instead) --
    # deliberately NOT dropped here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_audit_check_runs_check_id'), table_name='audit_check_runs', schema='company')
    op.drop_table('audit_check_runs', schema='company')
    op.drop_table('audit_checks', schema='company')
    # ### end Alembic commands ###
