"""add cascade delete for pipeline_stages child FKs

Revision ID: f7e6f9a04b17
Revises: 31800c28d250
Create Date: 2026-06-30 21:31:20.005017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e6f9a04b17'
down_revision: Union[str, Sequence[str], None] = '31800c28d250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pipeline_stage_dependencies_stage_id_fkey'), 'pipeline_stage_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stage_dependencies', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('pipeline_stage_gates_stage_id_fkey'), 'pipeline_stage_gates', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stage_gates', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('pipeline_stage_required_artifacts_stage_id_fkey'), 'pipeline_stage_required_artifacts', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stage_required_artifacts', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_stage_required_artifacts', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stage_required_artifacts_stage_id_fkey'), 'pipeline_stage_required_artifacts', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'pipeline_stage_gates', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stage_gates_stage_id_fkey'), 'pipeline_stage_gates', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'pipeline_stage_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stage_dependencies_stage_id_fkey'), 'pipeline_stage_dependencies', 'pipeline_stages', ['stage_id'], ['id'], source_schema='company', referent_schema='company')
    # ### end Alembic commands ###
